<?php 


/******
******* Implement hook_theme();
**********/


function become_a_section_theme($existing, $type, $theme, $path) {
   return array('become_a_section' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'courses'=> null,
                'students'=> null,
                'teachers'=> null,
                'total_price'=> null,
                'teache_role'=> null
            ),
        )
    );
}