<?php 


/******
******* Implement hook_theme();
**********/


function faq_block_theme($existing, $type, $theme, $path) {
   return array('faq_block' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'courses'=> null,
                'students'=> null,
                'teachers'=> null,
                'tuitionpaid'=> null
            ),
        )
    );
}