<?php 


/******
******* Implement hook_theme();
**********/


function become_teacher_theme($existing, $type, $theme, $path) {
   return array('becometeacherresult' =>                  // this is the name of the template
           array(
            'variables' => array(
                'title' => 'Default title',
                'student' => null,
                'video' => null,
                'teaching' => null
            ),
        )
    );
}